name: nuget
description: A Dart package that allows interaction with the NuGet Server API.
version: 0.1.0
repository: https://github.com/halildurmus/nuget
issue_tracker: https://github.com/halildurmus/nuget/issues

topics:
  - nuget
  - nuget-server-api
  - nuget-api
  - api

environment:
  sdk: ^3.1.0

dependencies:
  http: ^1.1.0
  version: ^3.0.2

dev_dependencies:
  checks: ^0.2.2
  dartwindows_lints: ^1.0.0
  melos: ^3.1.1
  test: ^1.24.6
