name: nuget
description: A Dart package that allows interaction with the NuGet Server API.
version: 0.1.1
repository: https://github.com/halildurmus/nuget
issue_tracker: https://github.com/halildurmus/nuget/issues

topics:
  - nuget
  - nuget-server-api
  - nuget-api
  - api

environment:
  sdk: ^3.3.0

dependencies:
  http: ^1.2.1
  version: ^3.0.2

dev_dependencies:
  checks: ^0.3.0
  dartwindows_lints: ^1.1.0
  melos: ">=4.1.0 <6.0.0"
  test: ^1.25.2
