name: nuget
description: A Dart package that allows interaction with the NuGet Server API.
version: 0.2.0
repository: https://github.com/halildurmus/nuget
issue_tracker: https://github.com/halildurmus/nuget/issues

topics:
  - nuget
  - nuget-server-api
  - nuget-api
  - api

environment:
  sdk: ^3.5.0

dependencies:
  http: ^1.2.2
  version: ^3.0.2

dev_dependencies:
  checks: ^0.3.0
  hooks:
    git:
      url: https://github.com/halildurmus/workflows.git
      path: packages/hooks
  lints:
    git:
      url: https://github.com/halildurmus/workflows.git
      path: packages/lints
  test: ^1.25.8
