name: nuget
description: TODO
version: 0.1.0
repository: https://github.com/halildurmus/nuget

environment:
  sdk: ^3.1.0

dependencies:
  http: ^1.1.0

dev_dependencies:
  checks: ^0.2.2
  dartwindows_lints: ^1.0.0
  melos: ^3.1.1
  test: ^1.24.6
